// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://cggghafhytiecnoxgbdj.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnZ2doYWZoeXRpZWNub3hnYmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA1NTY4ODIsImV4cCI6MjA0NjEzMjg4Mn0.RxEypqGlIIGLm5kO1n-Tw0uxh88-EFcm53Flkkyf2sE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);